extends:
  - airbnb-base
  - airbnb-typescript/base
settings:
  # append 'ts' extensions to Airbnb 'import/resolver' setting
  'import/resolver':
    node:
      extensions: ['.js', '.jsx', '.json', '.ts', '.tsx', '.d.ts']
overrides:
  - files: ['**/*.ts', '**/*.tsx', '**/*.js']
    parserOptions:
      project: 'tsconfig.json'
  - files: ['**/index.ts']
    rules:
      'import/prefer-default-export':
        - 0
rules:
  '@typescript-eslint/semi':
    - error
    - never
  no-restricted-syntax: 0
