extends:
  - 'eslint:recommended'
  - 'react-app'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
overrides:
  - files: ['**/*.ts?(x)']
    parserOptions:
      project: 'tsconfig.json'
    rules:
        '@typescript-eslint/adjacent-overload-signatures':
          - error
        '@typescript-eslint/array-type':
          - error
          - default: array-simple
        '@typescript-eslint/prefer-readonly':
          - error
        semi: 0
        '@typescript-eslint/semi':
          - error
          - never
        '@typescript-eslint/member-delimiter-style':
          - error
          - multiline:
              delimiter: none
            singleline:
              delimiter: comma
        '@typescript-eslint/type-annotation-spacing':
          - error
        '@typescript-eslint/prefer-regexp-exec':
          - error
        '@typescript-eslint/prefer-includes':
          - error
        func-call-spacing: 0
        '@typescript-eslint/func-call-spacing':
          - error
          - never
        no-useless-constructor: 0
        '@typescript-eslint/no-useless-constructor':
          - error
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never

  #Best practices
  array-callback-return:
    - error
  curly:
    - error
    - all
  dot-location:
    - error
    - property
  dot-notation:
    - warn
  eqeqeq:
    - error
    - always
  guard-for-in:
    - error
  no-alert:
    - error
  no-invalid-this:
    - error
  no-labels:
    - error
  no-lone-blocks:
    - error
  no-loop-func:
    - warn
  no-multi-spaces:
    - warn
  no-new-func:
    - error
  no-new-wrappers:
    - error
  no-return-assign:
    - warn
  no-return-await:
    - error
  no-sequences:
    - error
  no-throw-literal:
    - error
  no-unmodified-loop-condition:
    - warn
  prefer-promise-reject-errors:
    - error
  require-await:
    - warn
  wrap-iife:
    - error

  #Stylistic Issues
  array-bracket-newline:
    - warn
    - consistent
  array-bracket-spacing:
    - warn
    - always
  array-element-newline:
    - warn
    - consistent
  block-spacing:
    - warn
    - always
  brace-style:
    - warn
  comma-dangle:
    - warn
    - always-multiline
  comma-style:
    - warn
    - last
  computed-property-spacing:
    - warn
    - never
  eol-last:
    - warn
    - always
  func-call-spacing:
    - error
    - never
  #function-paren-newline:
  #  - warn
  #  - multiline
  jsx-quotes:
    - warn
    - prefer-double
  key-spacing:
    - warn
    - beforeColon: false
      afterColon: true
      mode: minimum
  keyword-spacing:
    - warn
    - before: true
      after: true
      overrides:
        if: { after: false }
        for: { after: false }
        while: { after: false }
        catch: { after: false }
        switch: { after: false }
        continue: { after: false }
        break: { after: false }
        debugger: { after: false }
  line-comment-position:
    - error
    - above
  lines-between-class-members:
    - warn
    - always
    - exceptAfterSingleLine: true
  max-len:
    - error
    - code: 120
      tabWidth: 4
      ignoreUrls: true
  multiline-ternary:
    - error
    - always-multiline
  newline-per-chained-call:
    - warn
  no-array-constructor:
    - error
  no-inline-comments:
    - error
  no-lonely-if:
    - error
  no-mixed-operators:
    - warn
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-trailing-spaces:
    - error
  no-unneeded-ternary:
    - error
    - defaultAssignment: false
  no-whitespace-before-property:
    - error
  object-curly-newline:
    - warn
    - multiline: true
      consistent: true
  object-curly-spacing:
    - warn
    - always
  object-property-newline:
    - warn
    - allowAllPropertiesOnSameLine: true
  operator-assignment:
    - warn
    - always
  operator-linebreak:
    - warn
    - after
  padded-blocks:
    - warn
    - never
    - allowSingleLineBlocks: true
  prefer-object-spread:
    - warn
  semi-spacing:
    - error
    - before: false
      after: true
  space-before-blocks:
    - warn
    - always
  space-before-function-paren:
    - warn
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens:
    - warn
    - never
  space-infix-ops:
    - warn
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  switch-colon-spacing:
    - error
  template-tag-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never

  #ECMAScript 6
  arrow-body-style:
    - warn
    - as-needed
  arrow-spacing:
    - warn
    - before: true
      after: true
  arrow-parens:
    - error
    - as-needed
  no-duplicate-imports:
    - error
  no-useless-computed-key:
    - error
  no-useless-constructor:
    - warn
  no-var:
    - error
  object-shorthand:
    - warn
  prefer-arrow-callback:
    - error
    - allowUnboundThis: true
  prefer-const:
    - error
  prefer-destructuring:
    - warn
    - VariableDeclarator:
        array: false
        object: true
      AssignmentExpression:
        array: false
        object: false
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  rest-spread-spacing:
    - error
  sort-imports:
    - warn
    - ignoreCase: true
      ignoreDeclarationSort: true
  template-curly-spacing:
    - error
    - never
